<a href="https://colab.research.google.com/github/Lanchenba-Mayanglambam/Data_Science-Amit-Sir/blob/main/lect_4_DS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np

In [17]:
# creating an array using numpy

arr = np.array([1,3,9,0,2])
print(arr)



# if there is a different data type then numpy array will convert all the element into a single datatype
arr1 = np.array([1,2,3,4,5,'9'])
print(arr1)


# QUESTION
np_arr = np.array([3,3,3,3,3.3,'hello',False])
print(bool(np_arr[-1]))
print(np_arr)

a = False
print(bool(a))

[1 3 9 0 2]
['1' '2' '3' '4' '5' '9']
True
['3' '3' '3' '3' '3.3' 'hello' 'False']
False


In [18]:
# zeros() function and it return aa numpy float by default to change the return datatype we use dtype
# zeros(3) creates a list(numpy array) of 0s
a = np.zeros(3)
print(a)

# zeros() functions as 2D Array
b = np.zeros((2,3))
print(b)

# multiple array
c = np.zeros((2,3,4),dtype=int)
print(c)
print(type(c[0][0][0]))

[0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]
<class 'numpy.int64'>


In [22]:
# empty() function creates a numpy array of garbage values
a = np.empty(4,dtype=int)
print(a)

[      538360907               0    481036337262 136068816232496]


In [25]:
# full() function creates a full numpy array of given value
a = np.full(4,5,dtype=int)
print(a)

[5 5 5 5]


In [33]:
# arange() function gives a range of element starting from 0 upto n-1   syntax -> (start,end,jump)
a = np.arange(0,5,1)
print(a)

[0 1 2 3 4]


In [41]:
# linspace() function  gives a numpy array  syntax -> (start,end,number of element want)
a = np.linspace(0,5,5,dtype=int)
print(a)

[0 2 5]


In [52]:
# shape and size
a = np.zeros((2,3),dtype=int)
print(a.size)
print(a.shape)

6
(2, 3)


In [80]:
# random.randomint() function and random.choice() function

# random.randit() gives random values syntax -> (start,stop,number of values want)
a = np.random.randint(5,20,5)
print(a)

# random.choice() gives random values from a given array  syntax -> (given array,number of values)
b = np.random.choice([1,3,5,7,9],2)
print(b)

[19  5 13  5  7]
[3 5]


In [110]:
# Operations
a = np.array([1,5,3])
b = np.array([2,4,9])
print(a*2)
print(a+b)
print(a/b)
print(a%b)



# Operations doesn't work on list
c = [1,2,3,4,5]
print(c*2)       #it will print c twice
d = [2,4,1,3,6]
# print(c*d)


[ 2 10  6]
[ 3  9 12]
[0.5        1.25       0.33333333]
[1 1 3]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [132]:
# reshape() function change the shape of the array
a = np.random.randint(2,15,6)
print(a)
print(" ")

b = a.reshape(2,3)
print(b)
print(" ")

c = b.transpose()
# print(c)

d = np.concatenate(b)
print(d)

[ 8 14  5 14  8  3]
 
[[ 8 14  5]
 [14  8  3]]
 
[ 8 14  5 14  8  3]


In [149]:
# concatenate() function
# a = np.random.randint(1,10,5)
# b = np.random.randint(1,10,5)
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8,9],[10,11,12]])

# print(a)
# print(b)
print(np.concatenate((a,b),axis=1))

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [152]:
# where() function  syntax -> (condition,(true then this,false then this))
a = np.random.randint(1,10,5)
b = np.random.randint(1,10,5)

print(a)
print(b)

c = np.where(b>2,b,a)
print(c)

[8 7 2 4 3]
[8 4 9 7 5]
[8 4 9 7 5]


In [153]:
# sort() function
a = np.random.randint(1,10,5)
print(a)
a.sort()
print(a)

[6 6 7 6 4]
[4 6 6 6 7]


In [157]:
# sum() function
a = np.random.randint(1,10,5)
b = np.random.randint(1,10,5)

print(a)
print(b)

c = np.sum(a)
d = b.sum()
print(c)
print(d)

[9 9 3 1 5]
[8 3 9 7 4]
27
31


In [158]:
# mean() function
a = np.random.randint(1,10,5)
print(a)

b = np.mean(a)
print(b)

[2 6 2 4 5]
3.8


In [159]:
# std() function
a = np.random.randint(1,10,5)
print(a)

b = np.std(a)
print(b)

[1 2 5 3 9]
2.8284271247461903


In [163]:
# unique() function return an array of unique elements
a = np.random.randint(1,10,5)
print(a)

b = np.unique(a)
print(b)

[5 8 6 4 7]
[4 5 6 7 8]


In [178]:
# matmul() function
# a = np.random.randint(1,10,5)
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2],[3,4],[5,6]])
# b = np.random.randint(1,10,5)

print(a)
print(b)

c = np.matmul(a,b)
print(c)


[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[22 28]
 [49 64]]


In [190]:
# practice
n = 9
score = np.zeros((n),dtype=int)
for i in range(n):
  a = input(int())
  score[i] = a

for i in range(n):
  print("On day ",(i+1)," ","Player score : ",score[i]," runs")

x = np.max(score)
print("Maximum Score of the Player : ",x," run")

y = np.min(score)
print("Minimum Score of the Player : ",y," run")

03
039
0100
059
069
030
050
020
040
On day  1   Player score :  3  runs
On day  2   Player score :  39  runs
On day  3   Player score :  100  runs
On day  4   Player score :  59  runs
On day  5   Player score :  69  runs
On day  6   Player score :  30  runs
On day  7   Player score :  50  runs
On day  8   Player score :  20  runs
On day  9   Player score :  40  runs
Maximum Score of the Player :  100  run
Minimum Score of the Player :  3  run


In [191]:
# taking input using split() function split convert all the elements into string
scores = input().split()
print(scores)


# to convert string into int
scores = [int(x) for x in scores]
print(scores)

1 2 3 4 5
['1', '2', '3', '4', '5']
[1, 2, 3, 4, 5]


In [192]:
# Changing of an element of an array change the value of both the array
a = np.array([3,3,3,3])

b = a
b[0] = 1

print(a,b)

[1 3 3 3] [1 3 3 3]
