<a href="https://colab.research.google.com/github/Lanchenba-Mayanglambam/Data_Science-Amit-Sir/blob/main/lect_5_DS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [34]:
a = np.random.randint(1,90,size=(5,5))
# print(a)
# b = a.reshape(5,5)
# print(b)
# for i in range(5):
#   mean = np.mean(b[i])
#   print("mean of row",(i+1)," : ",mean)

row = np.mean(a,axis=1)
print(row)

column = np.mean(a,axis=0)
print(column)


# replace even by -1
even = np.where(a%2 == 0,-1,a)
print(even)

sort_row = np.sort(a,axis=1)
sort_col = np.sort(a,axis=0)
print(sort_row)
print(sort_col)


# row and column wise sum
sum_row = np.sum(a,axis=1)
sum_col = np.sum(a,axis=0)
print(sum_row)
print(sum_col)


# number of "-ve" in each column
count_col = np.sum(np.where(even<0,1,0),axis=0)
print(count_col)



[3 2 3 2 3]


In [46]:
stock_level = np.random.randint(20,80,size=(5,5))
demand = np.random.randint(20,80,size=(5,5))
print(stock_level)
print(" ")
print(demand)
print(" ")


# remaining stocks
remaining_stock = stock_level - demand
print(remaining_stock)
print(" ")


# replace negative eith zero
replace_negative = np.where(remaining_stock<0,0,remaining_stock)
print(replace_negative)
print(" ")



# total shortage
total_shortage = np.sum(np.where(remaining_stock<0,remaining_stock,0))
print("total_shortage : ",total_shortage*(-1))
print(" ")



# product with zero stock
product_with_zero = np.sum(np.where(remaining_stock<=0,1,0),axis=0)
print("product_with_zero_stock : ",product_with_zero)
print(" ")



# sort each row on remaining stock
sort_row = np.sort(replace_negative,axis=1)
sort_col = np.sort(replace_negative,axis=0)
print(sort_row)
print(sort_col)


[[79 29 25 58 41]
 [72 26 45 22 29]
 [78 59 62 58 74]
 [43 33 42 75 67]
 [36 54 35 33 55]]
 
[[64 37 51 67 79]
 [49 66 25 23 57]
 [37 29 47 65 29]
 [33 68 37 78 76]
 [59 52 54 35 72]]
 
[[ 15  -8 -26  -9 -38]
 [ 23 -40  20  -1 -28]
 [ 41  30  15  -7  45]
 [ 10 -35   5  -3  -9]
 [-23   2 -19  -2 -17]]
 
[[15  0  0  0  0]
 [23  0 20  0  0]
 [41 30 15  0 45]
 [10  0  5  0  0]
 [ 0  2  0  0  0]]
 
total_shortage :  265
 
product_with_zero_stock :  [1 3 2 5 4]
 
[[ 0  0  0  0 15]
 [ 0  0  0 20 23]
 [ 0 15 30 41 45]
 [ 0  0  0  5 10]
 [ 0  0  0  0  2]]
[[ 0  0  0  0  0]
 [10  0  0  0  0]
 [15  0  5  0  0]
 [23  2 15  0  0]
 [41 30 20  0 45]]


In [65]:
# Pandas
import pandas as pd
file_ = pd.read_csv("student_data.csv")



print(file_)



# head function
# by default value is 5
print(file_.head(5))



# tail function
print(file_.tail())



      study_hours  attendance  sleep_hours  internet_usage  \
9995            2          58            9               7   
9996            7          98            6               9   
9997           10          44            8               5   
9998           10          75            7               5   
9999            2          70            6              11   

      assignments_completed  previous_score  exam_score placement_status  
9995                      8              88       69.31       Not Placed  
9996                      4              87      100.00           Placed  
9997                     10              37       95.94           Placed  
9998                      8              52       88.61           Placed  
9999                     16              52       78.96           Placed  
